version: 0.2

phases:
  install:
    runtime-version:
      nodejs: 12
    commands:
      - echo "Installing dependencies...."
      - npm install
  build:
    commands:
      - echo "Building Project..."
      - npm run build
  post_build:
    commands:
      - echo "Updating Project to S3..."
      - aws s3 sync build/ s3://kanishka-demo-app --delete
  